# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       libXv
Summary:    X.Org X11 libXv runtime library
Version:    1.0.6
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/releases/individual/lib/%{name}-%{version}.tar.bz2
Source100:  libXv.yaml
Patch0:     libXv-fix-pkgconfig.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(videoproto)
BuildRequires:  pkgconfig(xext)


%description
library for the X Video (Xv) extension to the X Window System


%package devel
Summary:    Development components for the libXv library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development library for the X Video (Xv) extension to the X Window System



%prep
%setup -q -n %{name}-%{version}

# libXv-fix-pkgconfig.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING ChangeLog
%{_libdir}/libXv.so.1
%{_libdir}/libXv.so.1.0.0
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%dir %{_includedir}/X11
%dir %{_includedir}/X11/extensions
%{_includedir}/X11/extensions/Xvlib.h
%{_libdir}/libXv.so
%{_libdir}/pkgconfig/xv.pc
#%dir %{_mandir}/man3x
%doc %{_mandir}/man3/*.3*
# << files devel

